### ISSUE TITLE
Tags: wrong alignement and spacing

### ISSUE THREAD

**Issue by Akryum** [posva/onlysponsors#16]
![image](https://user-images.githubusercontent.com/2798204/104091207-40b5a300-527c-11eb-9173-088bc7039a04.png)

**Comment by posva** [comment]
where do you see this? they are aligned on the explore page

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/105638830-3d720800-5e75-11eb-8ec8-3d67cce8e6c4.png)

On Firefox 84.0.2 (linux)

**Comment by Akryum** [comment]
It seems some tags have margins and others don't:
![image](https://user-images.githubusercontent.com/2798204/105638872-7c07c280-5e75-11eb-8d83-2f684b84d34b.png)

**Comment by posva** [comment]
Should be good now
