### ISSUE TITLE
502 error when viewing profile

### ISSUE THREAD

**Issue by vilhelmprytz** [posva/onlysponsors#19]
When I click "Your Profile", this page shows up.

![Profile](https://user-images.githubusercontent.com/15460993/104309482-87043f80-54d2-11eb-914b-276a47a8a526.png)

The API seems to return the following response (endpoint `https://onlysponsors.dev/api/users/vilhelmprytz`).

```json
{"error": {"code": "502", "message": "An error occurred with this application."}}
```

**Comment by posva** [comment]
Thanks! Fixed in the next deploy
