### ISSUE TITLE
H1 behavior is confusing

### ISSUE THREAD

**Issue by mholt** [posva/onlysponsors#21]
I often use `#` headings in Markdown documents -- IMO they can be treated differently from the page title.

The prompt uses a H1:

![Screenshot from 2021-01-28 12-24-45](https://user-images.githubusercontent.com/1128849/106188659-7a374b00-6164-11eb-862e-aeded9485c41.png)

But then I get an error when using one:

![Screenshot from 2021-01-28 12-24-52](https://user-images.githubusercontent.com/1128849/106188649-76a3c400-6164-11eb-8802-fbf1a05727ed.png)

It'd be nice if we could use H1's independent from the page title.

**Comment by posva** [comment]
You can, it's just a hint as you should only have one h1 for the whole article section. The comment will be update to `## Markdown`

**Comment by mholt** [comment]
Ah okay. Thank you!
