### ISSUE TITLE
Logout button not working on profile page

### ISSUE THREAD

**Issue by Akryum** [posva/onlysponsors#7]
Only on the profile page, the logout button is kinda "disabled" and does nothing.

![image](https://user-images.githubusercontent.com/2798204/103559515-8c500180-4eb6-11eb-9c7d-b1f98df61ae6.png)

**Comment by posva** [comment]
Is it fixed now?

**Comment by posva** [comment]
Seems to be fixed

**Comment by Akryum** [comment]
Not on my side, seems like the profile div is painted on top of the menu, preventing clicking on it:

![image](https://user-images.githubusercontent.com/2798204/103648869-d4762f00-4f5d-11eb-9d75-61a25f6181d3.png)

**Comment by Akryum** [comment]
More specifically this div:
![image](https://user-images.githubusercontent.com/2798204/103648991-01c2dd00-4f5e-11eb-96fe-c14af84100b9.png)

**Comment by posva** [comment]
aaah, I didn't see it was only there

**Comment by Akryum** [comment]
(In the screenshot I added a margin-top and then the button was clickable again)

**Comment by Akryum** [comment]
https://github.com/Akryum/v-tooltip :D

**Comment by posva** [comment]
just fixed with a z-index haha
