### ISSUE TITLE
Explore link at the top of homepage

### ISSUE THREAD

**Issue by Akryum** [posva/onlysponsors#8]
It would be nice to have the 'Explore' button at the top on the homepage too so we don't have to scroll down to click on it :cat2: 

![image](https://user-images.githubusercontent.com/2798204/103559607-b275a180-4eb6-11eb-96fa-ba9a29e308cb.png)

**Comment by carwack** [comment]
Wouldn't it be nice that if you're logged in, you directly go to the explore page?
Like it is my 'feed' and I can quickly scroll through the latest publications?

**Comment by posva** [comment]
I'm redirecting to explore by default now when logging in and also when visiting the homepage while being logged in
